macro(setup_flex_bison FLEX_INPUT BISON_INPUT FLEX_OUTPUT_SRC BISON_OUTPUT_SRC BISON_OUTPUT_HEADER)
    find_package(BISON REQUIRED)
    find_package(FLEX REQUIRED)

    set(PARSER_TARGET parser)
    set(SCANNER_TARGET scanner)
    set(GENERATED_SOURCES_DIR ${CMAKE_BINARY_DIR}/generated)

    make_directory(${GENERATED_SOURCES_DIR})

    BISON_TARGET(${PARSER_TARGET}
        ${BISON_INPUT}
        ${GENERATED_SOURCES_DIR}/${BISON_OUTPUT_SRC}
        DEFINES_FILE ${GENERATED_SOURCES_DIR}/${BISON_OUTPUT_HEADER}
    )

    FLEX_TARGET(${SCANNER_TARGET}
        ${FLEX_INPUT}
        ${GENERATED_SOURCES_DIR}/${FLEX_OUTPUT_SRC}
    )

    ADD_FLEX_BISON_DEPENDENCY(${SCANNER_TARGET} ${PARSER_TARGET})
endmacro()
